#  Este es un archivo de rubocop simple donde se deshabilitan
# muchas de las reglas que suele checkear rubocop, para dejar
# una base simple y se tengan que preocupar solo de ciertos "cops"

#  Al final de este archivo, si encuentras que te ayudaría a tener
# un código mas ordenado, puedes añadir todos los cops que creas convenientes.

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'app/views/**/*'
    - 'config/environments/*'
    - 'node_modules/**/*'

# Layout
Layout/LineLength: # *
  Max: 120
  Enabled: true
Layout/ClosingParenthesisIndentation: # *
  Enabled: true
Layout/IndentationStyle:
  Enabled: true
Layout/IndentationWidth: # *
  Enabled: true
  Width: 4
Layout/EmptyLinesAroundMethodBody: # *
  Enabled: true
Layout/EndOfLine:
  Enabled: False

# Naming
Naming/ConstantName: # *
  Enabled: true
Naming/FileName: # *
  Enabled: true
Naming/VariableName: # *
  Enabled: true

# Style 
Style/EmptyElse: # *
  Enabled: true
Style/Documentation:
  Enabled : false

# Lint
Lint/AmbiguousAssignment:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/UnreachableCode:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Lint/AssignmentInCondition:
  Enabled: true
Lint/EmptyExpression:
  Enabled: true

### Añade aquí todos los Cops que quieras:

Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false